site_name: Control de LEGO Mindstorms desde Python
site_url: https://semillero-ares.github.io/mindstorms-dc-python
theme:
  name: readthedocs # material
  locale: es

copyright: >
  Creado por <a href="https://github.com/davinsony">Davinson Castaño-Cano</a>.

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js